/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/worker/wrangler.jsonc --include-runtime=false --env-interface=JobsBindings apps/worker/worker-configuration.d.ts` (hash: 7cc04d3de4f454332ff806f044c9ce8a)
interface __BaseEnv_JobsBindings {
  HYPERDRIVE: Hyperdrive;
  JOBS_QUEUE: Queue;
  SIMULATION_DELAY_MS: "2000";
  PROVIDER_DEADLINE_MS: "60000";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env extends __BaseEnv_JobsBindings {}
}
interface JobsBindings extends __BaseEnv_JobsBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "SIMULATION_DELAY_MS" | "PROVIDER_DEADLINE_MS">> {}
}
declare module "*.txt" {
  const value: string;
  export default value;
}
declare module "*.html" {
  const value: string;
  export default value;
}
declare module "*.sql" {
  const value: string;
  export default value;
}
declare module "*.bin" {
  const value: ArrayBuffer;
  export default value;
}
declare module "*.wasm" {
  const value: WebAssembly.Module;
  export default value;
}
declare module "*.wasm?module" {
  const value: WebAssembly.Module;
  export default value;
}
