/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/worker/wrangler.jsonc --include-runtime=false --env-interface=JobsBindings apps/worker/worker-configuration.d.ts` (hash: 47891c92dbc6ad729de48fe32daadd61)
interface __BaseEnv_JobsBindings {
  DOCUMENTS: R2Bucket;
  HYPERDRIVE: Hyperdrive;
  JOBS_QUEUE: Queue;
  SIMULATION_DELAY_MS: "2000";
  PROVIDER_DEADLINE_MS: "60000";
  DEMO_INBOX_ENABLED: "true";
  BORROWER_ORIGIN: "https://keycade-borrower.kualia.workers.dev";
  REMINDER_FIRST_DELAY_MS: "86400000";
  REMINDER_SECOND_DELAY_MS: "259200000";
  ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env extends __BaseEnv_JobsBindings {}
}
interface JobsBindings extends __BaseEnv_JobsBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "SIMULATION_DELAY_MS"
        | "PROVIDER_DEADLINE_MS"
        | "DEMO_INBOX_ENABLED"
        | "BORROWER_ORIGIN"
        | "REMINDER_FIRST_DELAY_MS"
        | "REMINDER_SECOND_DELAY_MS"
        | "ENCRYPTION_KEY"
      >
    > {}
}
declare module "*.txt" {
  const value: string;
  export default value;
}
declare module "*.html" {
  const value: string;
  export default value;
}
declare module "*.sql" {
  const value: string;
  export default value;
}
declare module "*.bin" {
  const value: ArrayBuffer;
  export default value;
}
declare module "*.wasm" {
  const value: WebAssembly.Module;
  export default value;
}
declare module "*.wasm?module" {
  const value: WebAssembly.Module;
  export default value;
}
