/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/api/wrangler.jsonc --include-runtime=false --env-interface=ApiBindings apps/api/worker-configuration.d.ts` (hash: 7e79de5c972b03f8e66cab89926d3eaa)
interface __BaseEnv_ApiBindings {
  DOCUMENTS: R2Bucket;
  HYPERDRIVE: Hyperdrive;
  API_RATE_LIMITER: RateLimit;
  ALLOWED_ORIGINS: "https://keycade-bank-site.kualia.workers.dev,https://keycade-borrower.kualia.workers.dev,https://keycade-bank-console.kualia.workers.dev";
  JOBS: Fetcher /* keycade-jobs */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env extends __BaseEnv_ApiBindings {}
}
interface ApiBindings extends __BaseEnv_ApiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
declare module "*.txt" {
  const value: string;
  export default value;
}
declare module "*.html" {
  const value: string;
  export default value;
}
declare module "*.sql" {
  const value: string;
  export default value;
}
declare module "*.bin" {
  const value: ArrayBuffer;
  export default value;
}
declare module "*.wasm" {
  const value: WebAssembly.Module;
  export default value;
}
declare module "*.wasm?module" {
  const value: WebAssembly.Module;
  export default value;
}
